Blog_4/Blog_4/Models/Tag.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Blog_4.Models
{
    public class Tag
    {
        public int TagID { set; get; }
        [Required]
        [StringLength(100, ErrorMessage = "10 - 100 ki tu", MinimumLength = 10)]
        public String Content { set; get; }
        public virtual ICollection<Post> Posts { set; get; }
    }
}

Blog_4/Blog_4/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog_4.Models;

namespace Blog_4.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /Post/
        [AllowAnonymous]
        public ActionResult Index()
        {
            var posts = db.Posts.Include(p => p.UserProfile);
            return View(posts.ToList());
        }

        //
        // GET: /Post/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id = 0)
        {
            Post post = db.Posts.Find(id);
            ViewData["idpost"] = id;
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // GET: /Post/Create

        public ActionResult Create()
        {
            ViewBag.UserProfileUserID = new SelectList(db.UserProfiles, "UserId", "UserName");
            return View();
        }

        //
        // POST: /Post/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Post post, string content)
        {
            if (ModelState.IsValid)
            {
                post.DateCreated = DateTime.Now;
                List<Tag> Tags = new List<Tag>();
                string[] TagContent = content.Split(',');
                foreach (string item in TagContent)
                {
                    Tag tagExits = null;
                    var ListTag = db.Tags.Where(y => y.Content.Equals(item));
                    if (ListTag.Count() > 0)
                    {
                        tagExits = ListTag.First();
                        tagExits.Posts.Add(post);
                    }
                    else
                    {
                        tagExits = new Tag();
                        tagExits.Content = item;
                        tagExits.Posts = new List<Post>();
                        tagExits.Posts.Add(post);
                    }
                    Tags.Add(tagExits);
                }
                post.Tags = Tags;
                int userid = db.UserProfiles.Select(x => new { x.UserId, x.UserName }).
                    Where(y => y.UserName == User.Identity.Name).Single().UserId;
                post.UserProfileUserID = userid;
                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserProfileUserID = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserID);
            return View(post);
        }

        //
        // GET: /Post/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserProfileUserID = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserID);
            return View(post);
        }

        //
        // POST: /Post/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Post post)
        {
            if (ModelState.IsValid)
            {
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserProfileUserID = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserID);
            return View(post);
        }

        //
        // GET: /Post/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // POST: /Post/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Blog_4/Blog_4/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog_4.Models;

namespace Blog_4.Controllers
{
    public class TagController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /Tag/

        public ActionResult Index()
        {
            return View(db.Tags.ToList());
        }

        //
        // GET: /Tag/Details/5

        public ActionResult Details(int id = 0)
        {
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        //
        // GET: /Tag/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Tag/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Tag tag)
        {
            if (ModelState.IsValid)
            {
                db.Tags.Add(tag);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tag);
        }

        //
        // GET: /Tag/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        //
        // POST: /Tag/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Tag tag)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tag).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tag);
        }

        //
        // GET: /Tag/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        //
        // POST: /Tag/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tag tag = db.Tags.Find(id);
            db.Tags.Remove(tag);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        //
        // GET: /Tag/Search
        public ActionResult Search(int id = 0)
        {
            return View();
        }

        //
        //POST: /Tag/Search

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Search(Tag tag, string content)
        {
            List<Post> posts = new List<Post>();
            string TagContent = content;
            Tag tagExits = null;
            foreach (var stag in db.Tags)
            {
                if (stag.Content == content)
                {
                    tagExits = stag; break;
                }
            }
            return RedirectToAction("Searched/" + tagExits.TagID);
        }

        //
        // GET: /Tag/Searched
        public ActionResult Searched(int id =0)
        {
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }
    }
}

Blog_4/Blog_4/Views/Tag/Create.cshtml
@model Blog_4.Models.Tag

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Tag</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Content)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Content)
            @Html.ValidationMessageFor(model => model.Content)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blog_4/Blog_4/Views/Tag/Delete.cshtml
@model Blog_4.Models.Tag

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Tag</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Content)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Content)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Blog_4/Blog_4/Views/Tag/Details.cshtml
@model Blog_4.Models.Tag

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Tag</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Content)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Content)
    </div>
</fieldset>

@*<fieldset>
    <legend>Post</legend>
    @foreach(var post in Model.Posts)
    {
        <div>
            @Html.DisplayFor(p => post.Title)
        </div>
    }
</fieldset>*@
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.TagID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Blog_4/Blog_4/Views/Tag/Edit.cshtml
@model Blog_4.Models.Tag

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Tag</legend>

        @Html.HiddenFor(model => model.TagID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Content)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Content)
            @Html.ValidationMessageFor(model => model.Content)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blog_4/Blog_4/Views/Tag/Index.cshtml
@model IEnumerable<Blog_4.Models.Tag>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Content)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Content)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.TagID }) |
            @Html.ActionLink("Details", "Details", new { id=item.TagID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.TagID })
        </td>
    </tr>
}

</table>

Blog_4/Blog_4/Views/Tag/Search.cshtml
@model Blog_4.Models.Tag

@{
    ViewBag.Title = "Search";
}

<h2>Search post(s) by tag(s)</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Tag</legend>

        <div class="editor-field">
            @Html.EditorFor(model => new Blog_4.Models.Tag().Content)
            @Html.ValidationMessageFor(model => new Blog_4.Models.Tag().Content)
        </div>

        <p>
            <input type="submit" value="Search" />
        </p>
    </fieldset>
}

Blog_4/Blog_4/Views/Tag/Searched.cshtml
@model Blog_4.Models.Tag

@{
    ViewBag.Title = "Searched";
}

<h2>Searched</h2>

<fieldset>
    <legend>Post</legend>
    <p>Post Title: </p>
    @foreach(var post in Model.Posts)
    {
         @Html.ActionLink(""+post.Title, "Details/"+post.PostID,"Post")<br />
    }
</fieldset>
<p>
    @Html.ActionLink("Back to Search", "Search")
</p>